### ISSUE TITLE
AI26 scheduled analysis still fails after #146: worker crashes on 'ProjectNamespace' object has no attribute 'redis_stream'

### ISSUE THREAD

**Issue by TomiToivio** [TomiToivio/LaclauGPT-Data-Analysis#153]
## Problem

The scheduled AI26 analysis run still cannot complete, even after the stale-manifest guard from #146 was fixed. The re-freeze now works, but the worker then crashes on a runtime `AttributeError` before claiming any task.

Live evidence on Laskin, `main` @ `df4e82d`, working tree clean, private root `/mnt/workspace/LaclauGPT-Private`:

```text
[2026-09-18T12:23:13+03:00] AI26 manifest stale; re-freezing before scheduled analysis manifest_git=57cb5dd7... runtime_git=df4e82d7...
[2026-09-18T12:23:13+03:00] AI26 manifest re-frozen for scheduled analysis git=df4e82d7... tree=1341f2ea...
[2026-09-18T12:23:13+03:00] AI26 Laskin analysis start run=ai26-distributed-001 max_tasks=3 mode=once debug=0
Traceback (most recent call last):
  File ".../laclaugpt-analysis-worker", line 6, in <module>
    sys.exit(worker_main())
  File ".../contextual_entrypoints.py", line 86, in worker_main
    return legacy.main(argv)
  File ".../distributed_worker.py", line 542, in main
    worker, handoff = build_worker(binding, settings)
  File ".../distributed_worker.py", line 476, in build_worker
    queue = redis_queue_from_settings(
  File ".../task_queue.py", line 592, in redis_queue_from_settings
    stream=namespace.redis_stream("analysis", run_id),
AttributeError: 'ProjectNamespace' object has no attribute 'redis_stream'
[2026-09-18T12:23:14+03:00] AI26 Laskin analysis end status=1
```

No tasks are claimed, so the queue keeps growing while Collection keeps producing.

## Root cause

`RedisStreamQueue` construction in `redis_queue_from_settings()` (`src/laclaugpt_data_analysis/task_queue.py`) calls four namespace helpers:

```python
stream=namespace.redis_stream("analysis", run_id),
group=namespace.redis_group("analysis", run_id),
consumer=worker_id,
dead_letter_stream=namespace.redis_stream("analysis-dead", run_id),
heartbeat_key=namespace.redis_heartbeat("analysis", run_id, worker_id),
```

Three of them are **never defined anywhere in the repository**:

```text
$ grep -rn "def redis_stream\|def redis_group\|def redis_heartbeat" --include="*.py" .
(no matches)
```

`ProjectNamespace` (`src/laclaugpt_data_analysis/distributed.py`) defines `redis_key`, `stream_key`, `worker_key`, `lock_key`, `mongo_collection` and friends — but no `redis_stream`, `redis_group` or `redis_heartbeat`. It has no `__getattr__` fallback, so the access is a hard `AttributeError`.

The regression was introduced by `c182edc` ("Fix duplicate source_url key in Mongo failure persistence", 2026-09-17 21:10), which rewrote 491 lines of `task_queue.py` and replaced the old `namespace.redis_key(...)` key construction with `namespace.redis_stream(...)` / `redis_group(...)` / `redis_heartbeat(...)` calls that no class implements. The previous revision used `namespace.redis_key("tasks", run_id)` etc., which did exist.

## Why it was not caught

- `redis_queue_from_settings` has **no test coverage** (`grep -rn "redis_queue_from_settings" tests/` → no matches), so the broken attribute access never executes in CI.
- The crash only fires on the live distributed path (`LACLAUGPT_DATA_BACKEND=mongodb`, `LACLAUGPT_CACHE_BACKEND=redis`), i.e. from cron, not from the unit suite.
- It is masked behind the #146 failure: while the manifest was stale the worker failed earlier, at the freeze check, so this second breakage could not be seen.

## Impact

The analysis stage of the AI26 pipeline still produces nothing:
- newest `ai26__analyzed` record stays at `2026-09-17T16:28:28Z`;
- `ai26__processing` does not drain;
- the dashboard shows stale data;
- the failure is visible only in the run log.

This is the real reason the scheduled run is still dead after #146 was closed, and it is independent of #146.

## Suggested direction

1. Decide the intended namespace API and make it consistent — either implement `redis_stream` / `redis_group` / `redis_heartbeat` on `ProjectNamespace` (stream key, consumer-group name, heartbeat key), or point `redis_queue_from_settings` back at the existing `stream_key` / `redis_key` helpers. Whichever is chosen, the *same* helper family must be used for every Redis key in that function.
2. Add the missing test coverage: construct the queue from settings (`redis_queue_from_settings`) with a dummy URL and assert the four keys/groups are built without error, and that they match the documented namespace scheme.
3. Consider a cheap import-time/CI guard so a `namespace.<method>` reference that no class defines cannot land again.

## Environment

- Host: Laskin
- Repo: `/mnt/workspace/LaclauGPT-Data-Analysis`, `main` @ `df4e82d`, working tree clean
- Private root: `/mnt/workspace/LaclauGPT-Private`
- Model `gemma4:12b`, run `ai26-distributed-001`, schema 1.2.0
- Introduced by: `c182edc` (2026-09-17)
- Reproduce: `LACLAUGPT_PRIVATE_ROOT=/mnt/workspace/LaclauGPT-Private LACLAUGPT_MAX_TASKS=3 ./scripts/run_ai26_laskin.sh --once`

## Implementation completed

Fixed on `main` in commits:
- `f46414c` — use the existing `ProjectNamespace.stream_key`, `redis_key`, and `worker_key` API consistently in `redis_queue_from_settings()`.
- `c815665` — add a regression test that constructs the Redis queue from `Settings` without a live Redis server and pins the documented keys.

The queue now resolves to:
- task stream: `laclaugpt:ai26:stream:analysis:<run_id>:tasks`
- consumer group: `laclaugpt:ai26:group:analysis:<run_id>`
- dead-letter stream: `laclaugpt:ai26:stream:analysis:<run_id>:dead`
- heartbeat key: `laclaugpt:ai26:worker:analysis:<worker_id>`

This removes all runtime calls to the nonexistent `redis_stream`, `redis_group`, and `redis_heartbeat` methods.
